service: crypto-api

plugins:
  - serverless-webpack

custom:
  # Use stage option from cli, fallbacks to provider section
  stage: ${opt:stage, self:provider.stage}
  # serverless-webpack configuration
  webpack:
    webpackConfig: ./config/webpack/webpack.config.js
    includeModules: true

provider:
  name: aws
  stackTags:
    project: CryptoArb
  runtime: nodejs8.10
  stage: dev
  region: sa-east-1
  profile: CryptoArb
  memorySize: 128

functions:
  dashboard:
    handler: src/index-lambda.dashboard
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: dashboard
          method: get
          authorizer: aws_iam

resources:
  # Cognito
  - ${file(config/serverless/cognito-user-pool.yml)}
  - ${file(config/serverless/cognito-identity-pool.yml)}
